module.exports = [
    'Antiques & Collectibles',
    'Appliances',
    'Arts & Crafts',
    'Auto Parts',
    'Baby & Kids',
    'Bags & Luggage',
    'Bicycles',
    'Books, Movies & Music',
    'Electronics & Computers',
    'Furniture',
    'Garage Sale',
    'Garden',
    'Health & Beauty',
    'Home Sales',
    'Household',
    'Jewelry & Accessories',
    'Men\'s Clothing & Shoes',
    'Miscellaneous',
    'Mobile Phones',
    'Musical Instruments',
    'Pet Supplies',
    'Sports & Outdoors',
    'Tools',
    'Toys & Games',
    'Vehicles',
    'Video Games',
    'Women\'s Clothing & Shoes'
];