module.exports = [
    {value: 'Antiques & Collectibles', label: 'Antiques & Collectibles'},
    {value: 'Appliances', label: 'Appliances'},
    {value: 'Arts & Crafts', label: 'Arts & Crafts'},
    {value: 'Auto Parts', label: 'Auto Parts'},
    {value: 'Baby & Kids', label: 'Baby & Kids'},
    {value: 'Bags & Luggage', label: 'Bags & Luggage'},
    {value: 'Bicycles', label: 'Bicycles'},
    {value: 'Books, Movies & Music', label: 'Books, Movies & Music'},
    {value: 'Electronics & Computers', label: 'Electronics & Computers'},
    {value: 'Furniture', label: 'Furniture'},
    {value: 'Garage Sale', label: 'Garage Sale'},
    {value: 'Garden', label: 'Garden'},
    {value: 'Health & Beauty', label: 'Health & Beauty'},
    {value: 'Home Sales', label: 'Home Sales'},
    {value: 'Household', label: 'Household'},
    {value: 'Jewelry & Accessories', label: 'Jewelry & Accessories'},
    {value: 'Men\'s Clothing & Shoes', label: 'Men\'s Clothing & Shoes'},
    {value: 'Miscellaneous', label: 'Miscellaneous'},
    {value: 'Mobile Phones', label: 'Mobile Phones'},
    {value: 'Musical Instruments', label: 'Musical Instruments'},
    {value: 'Pet Supplies', label: 'Pet Supplies'},
    {value: 'Sports & Outdoors', label: 'Sports & Outdoors'},
    {value: 'Tools', label: 'Tools'},
    {value: 'Toys & Games', label: 'Toys & Games'},
    {value: 'Vehicles', label: 'Vehicles'},
    {value: 'Video Games', label: 'Video Games'},
    {value: 'Women\'s Clothing & Shoes', label: 'Women\'s Clothing & Shoes'}
];
